#!/bin/bash
#busside arvutamise script

echo -n "Sisesta reisijate arv"
read reisijad

echo -n "Mitu kohta on bussis"
read Bussis_kohti


bussid=$(($reisijad / $Bussis_kohti))
echo "$bussid bussi on vaja"

maha_jaanud=$(($reisijad % $Bussis_kohti))
echo "$maha_jaanud inimest jääb maha"
